### ISSUE TITLE
Repository taking up a lot of space

### ISSUE THREAD

**Issue by loneprajod** [TheLocehiliosan/yadm#135]
I just made my first commit and my `.yadm/repo.git/objects` folder takes up almost 1GB. I did not add any big file by mistake, just the configuration files of zsh. [Here](https://hastebin.com/xeseyodoxo.css) is the directory structure.

**Comment by TheLocehiliosan** [comment]
I'd be happy to help workout what's happened. But looking at the underlying directory structure isn't going to be particularly helpful.

What does this command show you?

    yadm rev-list --objects --all | yadm cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | sed -n 's/^blob //p' | sort --numeric-sort --key=2 | cut -c 1-12,41-

This should look at all of the commits to the yadm repo, examine the files in those commits, and what the size they contribute to the commit is. This also sorts so the largest are at the end of the output. I think this should help you track down the culprit.

**Comment by TheLocehiliosan** [comment]
I never received a response. Feel free to re-open this issue, and provide the information I asked about.

**Comment by kohane27** [comment]
Hello @ TheLocehiliosan  Hope you're doing well.

I'm not OP but I'm having the same issue.

After running the command provided:

```
d7ec2e62bb79 45579592 .local/share/atuin/history.db-wal
0f69d57d1657 46127552 .local/share/atuin/history.db-wal
624bb8397b13 49361752 .local/share/atuin/history.db-wal
b80d382d5391 50383512 .local/share/atuin/history.db-wal
2122ac94d08b 52266352 .local/share/atuin/history.db-wal
f8b7ecf758ea 53683632 .local/share/atuin/history.db-wal
7d1b954ce14b 56003192 .local/share/atuin/history.db-wal
18fe126ab16c 57387512 .local/share/atuin/history.db-wal
42819d304948 57787152 .local/share/atuin/history.db-wal
867c03f100ee 58899552 .local/share/atuin/history.db-wal
ce574d0315d4 63064872 .local/share/atuin/history.db-wal
5a90f560b64e 63406832 .local/share/atuin/history.db-wal
```

How do I proceed? I want to remove these big objects from the git history.

I did the following so that yadm would stop tracking:

```
yadm rm --cached /home/username/.local/share/atuin/history.db-wal
```

I tried using [bfg](https://rtyley.github.io/bfg-repo-cleaner/) but I encountered error:

```
➜ java -jar ~/repo/miscellaneous/bfg-1.14.0.jar --strip-blobs-bigger-than 10M /home/username/.local/share/yadm/repo.git

Using repo : /home/username/.local/share/yadm/repo.git

Scanning packfile for large blobs: 32426
Scanning packfile for large blobs completed in 110 ms.
Found 214 blob ids for large blobs - biggest=63406832 smallest=15866152
Total size (unpacked)=5339109832
Found 617 objects to protect
Found 550 commit-pointing refs : HEAD, refs/heads/main, refs/remotes/origin/main, ...

Protected commits
-----------------

These are your protected commits, and so their contents will NOT be altered:

java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at use.newer.java.Util.invokeMainMethod(Util.java:89)
        at use.newer.java.Util.executeMainProgram(Util.java:28)
        at use.newer.java.Util.checkJavaVersionAndExecuteMainProgram(Util.java:18)
        at use.newer.java.Version8.main(Version8.java:5)
Caused by: java.nio.file.AccessDeniedException: /home/username.bfg-report
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
        ... omitted ...
```

Any response is much appreciated. Thank you in advance!

**Comment by TheLocehiliosan** [comment]
Myself, I would probably use git filter branches, but that might be challenging to walk you thru in a GitHub issue. 

I'm guessing the problem you experienced with BFG is that it thinks you have a dirty working directory.

Try using BFG again, but only do so after cloning the repo elsewhere like you would a normal git repo. Clone the repo (using git), remove the big files from the history, and force push them back to origin.

Then you could remove the yadm repo locally and reclone it, as you might do on a new host.

**Comment by kohane27** [comment]
Hello @TheLocehiliosan  , thank you for willing to reply to this old issue and helping me. I really appreciate it.

I've made sure the `yadm` dir is clean:

```
➜ yadm status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit (use -u to show untracked files)
```

Then run it again:

```
➜ java -jar ~/repo/miscellaneous/bfg-1.14.0.jar --strip-blobs-bigger-than 15M /home/username/.local/share/yadm/repo.git

Using repo : /home/username/.local/share/yadm/repo.git

Scanning packfile for large blobs: 32426
Scanning packfile for large blobs completed in 308 ms.
Found 214 blob ids for large blobs - biggest=63406832 smallest=15866152
Total size (unpacked)=5339109832
Found 624 objects to protect
Found 550 commit-pointing refs : HEAD, refs/heads/main, refs/remotes/origin/main, ...

Protected commits
-----------------

These are your protected commits, and so their contents will NOT be altered:

java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at use.newer.java.Util.invokeMainMethod(Util.java:89)
        at use.newer.java.Util.executeMainProgram(Util.java:28)
        at use.newer.java.Util.checkJavaVersionAndExecuteMainProgram(Util.java:18)
        at use.newer.java.Version8.main(Version8.java:5)
Caused by: java.nio.file.AccessDeniedException: /home/username.bfg-report
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
        at java.base/java.nio.file.Files.createDirectory(Files.java:699)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:806)
        at java.base/java.nio.file.Files.createDirectories(Files.java:792)
        at com.madgag.git.bfg.cleaner.CLIReporter.reportsDir$lzycompute(Reporter.scala:64)
        at com.madgag.git.bfg.cleaner.CLIReporter.reportsDir(Reporter.scala:52)
        at com.madgag.git.bfg.cleaner.CLIReporter.reportProtectedCommitsAndTheirDirt(Reporter.scala:130)
        at com.madgag.git.bfg.cleaner.CLIReporter.reportObjectProtection(Reporter.scala:106)
        at com.madgag.git.bfg.cleaner.RepoRewriter$.rewrite(RepoRewriter.scala:96)
        at com.madgag.git.bfg.cli.Main$.$anonfun$new$1(Main.scala:59)
        at com.madgag.git.bfg.cli.Main$.$anonfun$new$1$adapted(Main.scala:34)
        at scala.Option.map(Option.scala:242)
        at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:34)
        at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:27)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at com.madgag.git.bfg.cli.Main$.main(Main.scala:27)
        at com.madgag.git.bfg.cli.Main.main(Main.scala)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 5 more
```

I think it's due to yadm uses a bare-bones git repo? Anyway, I tried `git filter-branch` and I got the following error:

```
.local/share/yadm/repo.git  main
➜ git filter-branch --tree-filter 'find . -size +15M -exec rm -f {} +' --prune-empty HEAD
You need to run this command from the toplevel of the working tree.
```

So I tried again:

```
~/.local/share/yadm
➜ git filter-branch --tree-filter 'find . -size +15M -exec rm -f {} +' --prune-empty HEAD
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I understand that yadm uses a bare-bones git repo. So I'm pretty stuck. Any help is much more appreciated again. Thank you again!

**Comment by TheLocehiliosan** [comment]
If it is due to a bare repo, the easy solution will be to clone the repo with git (to some other location), and then perform the surgery on your repo with one of those methods. Then push the changes back to the origin.

Do you still get those errors of you try that?

**Comment by kohane27** [comment]
@TheLocehiliosan 

Thank you so much! The method you suggested works! Below is what I did if anyone is interested:

1. `git clone git@gitlab.com/your_dotfiles.git ~/Downloads/your_dotfiles`

2. use [bfg](https://rtyley.github.io/bfg-repo-cleaner/):

```bash
java -jar ~/Downloads/bfg-1.14.0.jar --strip-blobs-bigger-than 15M ~/Downloads/your_dotfiles
cd your_dotfiles
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

3. `git push --force` to push changes back to gitlab

4. back up yadm's original local `repo.git`:

```bash
mv ~/.local/share/yadm/repo.git ~/Downloads/
```

5. `yadm` clone again:

```
yadm clone git@gitlab.com/your_dotfiles.git
```

6. Verify the object sizes:

```bash
cd ~/.local/share/yadm/repo.git
dust ./
```

Cheers!

**Comment by TheLocehiliosan** [comment]
Glad it worked. Cheers
